apiVersion: v2
name: berg-controller
description: Kubernetes controller for managing Berg CTF challenge instances
type: application
version: 1.0.2
appVersion: "1.0.2"
keywords:
  - berg
  - kubernetes
  - ctf
  - challenge-instance
  - instancing
maintainers:
  - name: cfi2017
